services:
  postgres:
    image: postgres:latest
    container_name: sugar
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  flyway:
    image: flyway/flyway:9
    depends_on:
      - postgres
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./migrations:/flyway/sql
    command: migrate

  sugar-bot:
    build: .
    container_name: sugar-bot
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      POSTGRES_DB: ${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      my_chat_token: ${my_chat_token}
      LOGGING_LEVEL_SUGAR: ${LOGGING_LEVEL_SUGAR}
      ADMIN: ${ADMIN}

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
