package sugar.telegram.enums;

public enum State {
    SUGAR,
    INSULIN,
    NOTE,
    REMOVE,
    GET_SUGAR_BY_ID,
    WAIT_ID_FOR_UPDATE,
    WAIT_SUGAR_FOR_UPDATE,
    WAIT_INSULIN_FOR_UPDATE,
    WAIT_NOTE_FOR_UPDATE,
    UPDATE_START,
    SET_TIME_FOR_NOTIFY,
    WAITING_FOR_NOTIFY
}
